### ISSUE TITLE
Cannot open game quickly after putting bayohook

### ISSUE THREAD

**Issue by CrazyingBlack** [SSSiyan/BayoHook#17]
I used bayohook before and could open the game normally and quickly and use it normally in the game. When I opened the game as usual today, it took about 5-6 minutes to start the game (I even thought it wouldn't work). After I deleted the bayohook, the game started quickly and normally.
I don't know where to export the bug report. Do you know why it happened?

**Comment by SSSiyan** [comment]
Try monitoring your antivirus in task manager (or disabling it temporarily) to see if that's affecting it; maybe it's being scanned each boot,

**Comment by CrazyingBlack** [comment]
> Try monitoring your antivirus in task manager (or disabling it temporarily) to see if that's affecting it; maybe it's being scanned each boot,

Thank you for your suggestion. I still failed after trying various methods, including the method you mentioned. After a few hours it returned to normal and I could use bayohook normally. I think it might be related to something on steam.
Thank you very much for your reply.
