### ISSUE TITLE
Suggestion : Witch Time

### ISSUE THREAD

**Issue by St1nGxD** [SSSiyan/BayoHook#6]
we should have "Always/Auto Witch Time" like even if you mistime your dodge, you still get Witch Time to work, and i've noticed through my playthrough that some attacks when i try to Witch Time them it doesn't work even though the game slows down and i can hear the slow mo SFX, if there's a fix for that that would be nice, thanks in advance!

**Comment by SSSiyan** [comment]
Added always witch time in https://github.com/SSSiyan/BayoHook/commit/a714dbfcf6185ef0e854f7840dd06591ef76729c, this just gives you standard witch time even if you don't dodge an attack.
Attempted to make specifically dodging any attack give you witch time but am too dumb, I'll figure it out sometime.
Here's a build
[dinput8.zip](https://github.com/SSSiyan/BayoHook/files/10561274/dinput8.zip)
